spring:
  datasource:
    url: jdbc:postgresql://db:5432/balihome  # "db" matches the service name in docker-compose.yml
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
